packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@better-auth/cli": 1.4.0-beta.9
  "@eslint/js": ^9.39.2
  "@nestjs/common": ^11.1.11
  "@nestjs/core": ^11.1.11
  "@tailwindcss/postcss": ^4.1.18
  "@tanstack/react-form": ^1.27.7
  "@tanstack/react-query": ^5.90.16
  "@trpc/client": ^11.8.1
  "@trpc/server": ^11.8.1
  "@trpc/tanstack-react-query": ^11.8.1
  "@turbo/gen": ^2.7.2
  "@types/node": ^22.19.3
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  better-auth: 1.4.0-beta.9
  eslint: ^9.39.2
  next: 16.1.1
  prettier: ^3.7.4
  react: 19.2.3
  react-dom: 19.2.3
  tailwindcss: ^4.1.18
  turbo: ^2.7.2
  typescript: ^5.9.3
  typescript-eslint: ^8.51.0
  zod: ^4.3.4

catalogs:
  react19:
    "@types/react": ^19.2.7
    "@types/react-dom": ^19.2.3
    react: 19.2.3
    react-dom: 19.2.3

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@scarf/scarf"
  - argon2
  - better-sqlite3
  - core-js-pure
  - esbuild
  - grpc-tools
  - sharp
  - unrs-resolver

overrides:
  "@types/minimatch": 5.1.2
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
